# Generated by Django 5.1.1 on 2024-11-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_favorites_artist'),
    ]

    operations = [
         migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION increment_streams()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE music_song
                SET streams = streams + 1
                WHERE id = NEW.song_id;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER song_play_trigger
            AFTER INSERT ON music_listen
            FOR EACH ROW
            EXECUTE FUNCTION increment_streams();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS song_play_trigger ON music_listen;
            DROP FUNCTION IF EXISTS increment_streams;
            """
        ),
    ]
