# Generated by Django 5.1.3 on 2025-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_user_country_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
