# Generated by Django 5.1.3 on 2025-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_songrequest_album_songrequest_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
