# Generated by Django 5.1.3 on 2025-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
