# Generated by Django 5.1.1 on 2024-11-29 16:30

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artistfollow'),  # Update if your previous migration number differs
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION update_followers_on_follow()
            RETURNS TRIGGER AS $$
            BEGIN
                -- Increase the followers count by 1
                UPDATE music_artist
                SET followers = followers + 1
                WHERE id = NEW.artist_id;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER update_followers_on_artist_follow
            AFTER INSERT ON music_artistfollow
            FOR EACH ROW
            EXECUTE FUNCTION update_followers_on_follow();


            CREATE OR REPLACE FUNCTION update_followers_on_unfollow()
            RETURNS TRIGGER AS $$
            BEGIN
                -- Decrease the followers count of the artist by 1
                UPDATE music_artist
                SET followers = followers - 1
                WHERE id = OLD.artist_id;
                RETURN OLD;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER update_followers_on_artist_unfollow
            AFTER DELETE ON music_artistfollow
            FOR EACH ROW
            EXECUTE FUNCTION update_followers_on_unfollow();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS update_followers_on_artist_follow ON music_artistfollow;
            DROP TRIGGER IF EXISTS update_followers_on_artist_unfollow ON music_artistfollow;
            DROP FUNCTION IF EXISTS update_followers_on_follow;
            DROP FUNCTION IF EXISTS update_followers_on_unfollow;
            """
        ),
    ]
