# Generated by Django 5.1.3 on 2025-04-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artistfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
