# Generated by Django 5.1.1 on 2025-04-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_songrequest_file_url'),
        ('music', '0009_update_followers_triggers'),
    ]

    operations = [
    ]
